### ISSUE TITLE
Allow COORS for orders route

### ISSUE THREAD

**Issue by gobyrne** [kheaactua/diplomacy-engine#10]
```
 http://diplomacy2.asilika.com:9494/api/rest/matches/2/empires/7/orders. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 400.
```

Is that the right route for posting orders to? It will need the correct headers.

**Comment by kheaactua** [comment]
Didn't that work last night?  Nothing has changed since then..

**Comment by kheaactua** [comment]
Oh, might be because of php errors.. sec..

**Comment by kheaactua** [comment]
That was on the `diplomacy2.asilika.com:9494/api/rest/matches/49/empires/168/territories` route?  If so, fixed now.

**Comment by gobyrne** [comment]
It is only occurring on the ORDERS route. It might be because it's a POST and the rest of the routes are GET.  (it's still occurring)

**Comment by kheaactua** [comment]
Hmm, you should be seeing

Headers:

``` text
Access-Control-Allow-Credentials → true
Access-Control-Allow-Headers → DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type
Access-Control-Allow-Methods → GET, POST, OPTIONS, DELETE, PUT, PATH
Access-Control-Allow-Origin → *
Connection → keep-alive
Content-Length → 158
Content-Type → application/json; charset=utf-8
Date → Wed, 27 May 2015 02:56:42 GMT
Server → nginx/1.6.2 (Ubuntu)
X-Powered-By → PHP/5.5.12-2ubuntu4.4
```

Payload

``` text
{
    "status": 200,
    "data": {
        "code": -100,
        "msg": "Cannot find route on DiplomacyEngineRestApi\\v1\\Match",
        "data": null
    }
}
```

at `diplomacy2.asilika.com:9494/api/rest/matches/1/empires/2/orders`

Which is wrong, but the headers should still be right.  I'll see what happens when I fix it.

Oh.. btw.. all the IDs changed again.. :(  Sorry :disappointed:

**Comment by gobyrne** [comment]
Ids changing doesn't affect me, they are not hardcoded so don't worry about it. I'll try it again.

**Comment by gobyrne** [comment]
Well, we never really figured out what was causing my error, but it doesn't seem to be a problem anymore.

**Comment by kheaactua** [comment]
Sweet.   Today sometime I'll set you up with a sender hosted at Carleton.   It'll be on a different webserver,  so should offer you're prism a little diversity,  or at least the ability to compare servers

**Comment by kheaactua** [comment]
Meant to say, was actually really relieved, as last night in bed I realized that I hadn't actually addressed that specific issue. :)  Can you try the POST route again?

Also, check out `$resource` (or `ngResource`) [here](https://docs.angularjs.org/api/ngResource/service/$resource), it's a super easy way to implement REST in an OO way in JS.  I've used it a lot in the past.  I just forget how to use it with collections (arrays of objects, basically almost everything you're retreiving)
